# -*- coding: utf-8 -*-
"""Math3349_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-y4_3pkqkr5O8IkaDgys-15qxg8Le7I1
"""

# This whole part for FDM, we don't normalize for PINNs
import jax.numpy as jnp
from jax import jit

# Set up
N = 100
h = 1.0 / (N - 1)
T = jnp.zeros((N, N))

# normalization. Referred to equation (2)
T = T.at[-1, :].set(1.0)                     # Top wall: Θ = 1
T = T.at[0, :].set(0.0)                      # Bottom wall: Θ = 0
T = T.at[:, 0].set(jnp.linspace(0, 1, N))    # Left wall: linear y
T = T.at[:, -1].set(jnp.linspace(0, 1, N))   # Right wall: linear y

@jit
# Whole things referred to equation (6)
def update(T):
    T_new = T.at[1:-1, 1:-1].set(
        0.25 * (
            T[2:, 1:-1] +  # u_{i+1,j}
            T[:-2, 1:-1] + # u_{i-1,j}
            T[1:-1, 2:] +  # u_{i,j+1}
            T[1:-1, :-2]   # u_{i,j-1}
        )
    )
    return T_new

# Iterative solver
def solve_laplace(T, max_iters=10000, tol=1e-6):
    for _ in range(max_iters):
        T_new = update(T)
        error = jnp.max(jnp.abs(T_new - T))
        T = T_new
        if error < tol:
            break
    return T

T_sol = solve_laplace(T)

import matplotlib.pyplot as plt

plt.imshow(T_sol, cmap='inferno', origin='lower')
plt.colorbar(label="Normalized Temperature")
plt.title("Laplace Equation Solution")
plt.show()

# Load libraries
import jax
import jax.numpy as jnp
import optax
import matplotlib.pyplot as plt
from jax import random
import math
import time
import os
import pandas as pd
import numpy as np
from jax import vmap

os.system("pip3 install --upgrade git+https://github.com/dmarcondes/JINNAX")
os.system("pip3 install dill")
os.system("pip3 install --upgrade git+https://github.com/dmarcondes/genree")

from jinnax import data as jd
from jinnax import nn as nn

# Hyperparameters
N = 100               # resolution of FDM reference
lr = 1e-3
x = jnp.linspace(0, 1, N)
y = jnp.linspace(0, 1, N)
X, Y = jnp.meshgrid(x, y)

# Temperature conversion
def denormalize_temperature(theta, T_min, T_max):
    return theta * (T_max - T_min) + T_min

# Build multi-layer perception
def init_mlp(sizes, key):
    params = []  #Initializes an empty list to hold the parameters for each layer
    keys = random.split(key, len(sizes))
    for m, n, k in zip(sizes[:-1], sizes[1:], keys):
        W = random.normal(k, (n, m)) * jnp.sqrt(2.0 / m)  # W is weight matrix
        b = jnp.zeros(n)      # b is Bias vector
        params.append((W, b))    # Together (W,b) fully defines the transformation at each layer)
    return params

def predict(params, x):            # During training, W and b are updated by Adam optimizer
    for W, b in params[:-1]:
        x = jnp.tanh(x @ W.T + b)
    W, b = params[-1]
    return (x @ W.T + b).squeeze(-1)

def laplace_pde(u_fn, x):
    def u(xy): return u_fn(xy)
    grad_u = jax.jacrev(u)
    hess_u = jax.jacrev(grad_u)
    hessian = vmap(hess_u)(x)
    return jnp.trace(hessian, axis1=1, axis2=2)  # laplacian

# Boundary condition
def generate_boundary_conditions(N, mode, T_min, T_max):
    x = jnp.linspace(0, 1, N)
    boundary_coords = []
    boundary_values = []
    if mode == 'partial':
        for i in range(N):
            boundary_coords.append([x[i], 0.0])  # bottom
            boundary_values.append(T_min)
            boundary_coords.append([x[i], 1.0])  # top
            boundary_values.append(T_max)
    elif mode == 'none':
        return jnp.empty((0, 2)), jnp.empty((0,))
    return jnp.array(boundary_coords), jnp.array(boundary_values)

# Define a train_PINN_2D function by ourself, since the built-in function train_PINN only works for 1D with time variable functions
    # Want neutral network optimization:  \[u_\theta(x, y) = \text{MLP}_\theta(x, y)\]
def train_PINN_2D(data, width, pde, test_data, epochs,k):
    # initializes a random number generator for JAX
    params = init_mlp(width, k)  #constructs a multi-layer perceptron (MLP) with layer sizes `width`
    optimizer = optax.adam(lr)
    opt_state = optimizer.init(params)  #params is list of weights and biases \(\theta = \{W_i, b_i\}\)


    def loss_fn(params):   # Key formula for PINN
        pred_sensor = predict(params, data['sensor'])  # Sensor loss
        pred_boundary = predict(params, data['boundary'])   # Boundary condition loss
        pde_res = pde(lambda x: predict(params, x), data['sensor'])   #PDE residual loss
        return (
            jnp.mean((pred_sensor - data['usensor']) ** 2) +
            jnp.mean((pred_boundary - data['uboundary']) ** 2) +
            jnp.mean(pde_res ** 2)
        )

    # The training step
    @jit
    def train_step(opt_state, params):
        loss, grads = jax.value_and_grad(loss_fn)(params)
        updates, opt_state = optimizer.update(grads, opt_state)
        params = optax.apply_updates(params, updates)
        return params, opt_state, loss

    for epoch in range(epochs):
        params, opt_state, loss = train_step(opt_state, params)
        if epoch % 500 == 0:
            print(f"Epoch {epoch}, Loss: {loss:.5f}")

    return {'u': lambda x: predict(params, x), 'params': params}

# Run the actual experiment
def run_noise_experiments_across_levels(cfg):
    noise_levels = [0.0, 0.01, 0.02, 0.05, 0.10]
    labels = [f"{int(nl*100)}%" for nl in noise_levels]
    results = []

    for i, nl in enumerate(noise_levels):
        print(f"Running {labels[i]} noise level...")
        errors = []

        # True temperature field (precomputed FDM result)
        Theta_true = Y
        T_true = denormalize_temperature(Theta_true, cfg['T_min'], cfg['T_max'])
        test_coords = jnp.stack([X.ravel(), Y.ravel()], axis=-1)
        test_data = {'coords': test_coords, 'u_true': T_true.ravel()}

        # Sensor coordinates
        idx = jnp.linspace(0, N - 1, cfg['grid_size'], dtype=int)
        sensor_coords = jnp.array([[x[i], y[j]] for i in idx for j in idx])
        clean_values = jnp.array([T_true[j, i] for i in idx for j in idx])

        # Add noise and train multiple runs
        keys = random.split(random.PRNGKey(1000 + i), num=2 * 10)
        for r in range(10):
            key_noise = keys[2 * r]
            key_train = keys[2 * r + 1]
            noise = nl * jnp.std(clean_values) * random.normal(key_noise, shape=clean_values.shape)
            noisy_sensor = clean_values + noise

            bc_coords, bc_values = generate_boundary_conditions(N, cfg['boundary_mode'], cfg['T_min'], cfg['T_max'])
            train_data = {
                'sensor': sensor_coords,
                'usensor': noisy_sensor,
                'boundary': bc_coords,
                'uboundary': bc_values
            }

            fit = train_PINN_2D(train_data, cfg['width'], laplace_pde, test_data, cfg['epochs'], key_train)
            u_pred = fit['u'](test_coords)
            rel_l2 = jnp.linalg.norm(u_pred - test_data['u_true']) / jnp.linalg.norm(test_data['u_true'])
            errors.append(float(rel_l2))

            # Plot for the first run of each noise level
            if r == 0:
                u_pred_2d = np.array(u_pred).reshape(N, N)
                error_map = np.abs(u_pred_2d - np.array(T_true))

                plt.figure(figsize=(15, 4))

                # Ground truth
                plt.subplot(1, 3, 1)
                plt.imshow(T_true, cmap='plasma', origin='lower', extent=[0, 1, 0, 1])
                plt.title("Ground Truth")
                plt.colorbar()

                # PINN prediction
                plt.subplot(1, 3, 2)
                plt.imshow(u_pred_2d, cmap='plasma', origin='lower', extent=[0, 1, 0, 1])
                plt.title(f"PINN Prediction — Noise {labels[i]}")
                plt.colorbar()

                # Absolute error
                plt.subplot(1, 3, 3)
                plt.imshow(error_map, cmap='viridis', origin='lower', extent=[0, 1, 0, 1])
                plt.title("Absolute Error (|True - PINN|)")
                plt.colorbar()

                # Summary title
                plt.suptitle(
                    f"Noise {labels[i]} — BC: {cfg['boundary_mode']} — Temp {cfg['T_min']}°C to {cfg['T_max']}°C\nL2 Error: {rel_l2:.6f}",
                    fontsize=12
                )

                plt.tight_layout()
                plt.show()

        results.append(errors)

    # Boxplot for all noise levels
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.set_yscale('log')
    bp = ax.boxplot(results, patch_artist=True, showmeans=True,
                    boxprops=dict(facecolor='lightgreen', color='black'),
                    meanprops=dict(color='red', linestyle='--'),
                    medianprops=dict(color='black'))
    ax.set_xticks(np.arange(1, len(labels) + 1))
    ax.set_xticklabels(labels)
    ax.set_xlabel("Noise Level")
    ax.set_ylabel("Relative L2 Error (log scale)")
    ax.set_title(f"PINN Performance vs Noise Level (BC: {cfg['boundary_mode']})")
    ax.grid(True, linestyle='--', alpha=0.6)
    plt.tight_layout()
    plt.show()
    # Summary table
    summary_data = []
    for i, errs in enumerate(results):
        mean = np.mean(errs)
        std = np.std(errs)
        summary_data.append((labels[i], mean, std))

    df = pd.DataFrame(summary_data, columns=["Noise Level", "Mean L2 Error", "Std Dev"])
    print("\nSummary Table:")
    print(df.to_string(index=False))
    return results, labels

def compare_boundary_conditions(cfg):
    cfg_partial = cfg.copy()
    cfg_partial['boundary_mode'] = 'partial'
    partial_results, labels = run_noise_experiments_across_levels(cfg_partial)

    cfg_none = cfg.copy()
    cfg_none['boundary_mode'] = 'none'
    none_results, _ = run_noise_experiments_across_levels(cfg_none)

    # Combine the results: [0%-partial, 0%-none, 1%-partial, 1%-none, ...]
    combined_results = []
    combined_labels = []
    for i in range(len(labels)):
        combined_results.append(partial_results[i])
        combined_labels.append(f"{labels[i]} (partial)")
        combined_results.append(none_results[i])
        combined_labels.append(f"{labels[i]} (none)")

    # Side-by-side boxplot
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.set_yscale('log')

    # Define spacing for side-by-side groupings
    num_groups = len(partial_results)
    bar_width = 0.3
    positions_partial = np.arange(num_groups)
    positions_none = positions_partial + bar_width

    # Plot partial BC results (e.g., in red)
    bp1 = ax.boxplot(partial_results, positions=positions_partial, widths=bar_width,
                 patch_artist=True, showmeans=True,
                 boxprops=dict(facecolor='salmon', color='black'),
                 meanprops=dict(marker='D', markerfacecolor='black', markeredgecolor='black'),
                 medianprops=dict(color='black'))

    # Plot no BC results (e.g., in blue)
    bp2 = ax.boxplot(none_results, positions=positions_none, widths=bar_width,
                 patch_artist=True, showmeans=True,
                 boxprops=dict(facecolor='skyblue', color='black'),
                 meanprops=dict(marker='D', markerfacecolor='black', markeredgecolor='black'),
                 medianprops=dict(color='black'))

    # Set x-axis ticks in between paired bars
    group_centers = (positions_partial + positions_none) / 2
    ax.set_xticks(group_centers)
    ax.set_xticklabels(labels)

    ax.set_xlabel("Noise Level")
    ax.set_ylabel("Relative L2 Error (log scale)")
    ax.set_title("Comparison of PINN Performance: Partial vs No Boundary Condition")
    ax.grid(True, linestyle='--', alpha=0.6)

    # Add legend
    from matplotlib.patches import Patch
    ax.legend([Patch(facecolor='salmon'), Patch(facecolor='skyblue')],
             ['Partial BC', 'No BC'], loc='upper left')

cfg = {
    'T_min': 25.0,
    'T_max': 50.0,
    'grid_size': 5,
    'epochs': 50000,
    'width': [2] + 8 * [20] + [1],
    'boundary_mode': 'partial'
}
compare_boundary_conditions(cfg)